---
title: "Lec9 Logistic Regression"
output: html_notebook
---
## Example 2-> AIDS

### 1. Get Data
```{r}
race<-c("w","w","b","b")
AZTuse<-c("yes","no","yes","no")
yes<-c(14,32,11,12)
no<-c(93,81,52,43)
aids<-data.frame(race,AZTuse,yes,no)
aids
```

### 2. Test H0: $\beta_1 = \beta_2 = \cdots = \beta_p = 0$
```{r}
logit1<-glm(cbind(yes,no)~factor(race)+factor(AZTuse),family=binomial)
logit1
```
The residual deviance is 1.384 with one degree of freedom (4 profiles, 3 parameters).
THe p-value is:
```{r}
pchisq(1.384, df=1, lower.tail = FALSE)
```
* pchisq中的lower.tail表明是求P[X>x]，右边. TRUE是P[X<= x]，左边。

不过这里比较不是直接拿residual deviance.

H0: $\beta_1 = \beta_2 = \cdots = \beta_p = 0$。
那么test H0, 是Null Deviance - Residual Devaince = 8.35-1.384 = 6.966.
而对应的chi square是：
```{r}
qchisq(0.95, 2)
```
Null Deviance对应的df是4-1 = 3. Residual Deviance是4-3 = 1.
所以二者差的df是2.
那么Null Deviance - Residual Devaince > $\chi_2^2(0.95)$，所以reject H0.
至少有一个$\beta_i$不是0.

也可以通过p-value做：
```{r}
pchisq(6.966, df=2, lower.tail = FALSE)
```
同样reject H0.

### 3. Test H0: $\beta_1 = 0$


