\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={HW8-ADA},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{HW8-ADA}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  

\begin{document}
\maketitle

\hypertarget{jing-qian-jq2282}{%
\section{Jing Qian (jq2282)}\label{jing-qian-jq2282}}

\hypertarget{a.-find-the-density-f_tt-of-t.}{%
\paragraph{\texorpdfstring{1.a. Find the density, \(f_T(t)\) of
\(T\).}{1.a. Find the density, f\_T(t) of T.}}\label{a.-find-the-density-f_tt-of-t.}}

\(f_T(t) = -\frac{d}{d\ t}S(t) = \alpha^{\beta}\beta\ t^{\beta-1} e^{-(\alpha t)^{\beta}}\).

\hypertarget{b.-find-the-hazard-function-lambdat-of-t.}{%
\paragraph{\texorpdfstring{1.b. Find the hazard function \(\lambda(t)\)
of
\(T\).}{1.b. Find the hazard function \textbackslash{}lambda(t) of T.}}\label{b.-find-the-hazard-function-lambdat-of-t.}}

\(\lambda (t) = \frac{f_T(t)}{S(t)} = \frac{\alpha^{\beta}\beta\ t^{\beta-1} e^{-(\alpha t)^{\beta}}}{e^{-(\alpha t)^{\beta}}} = \alpha^{\beta}\beta\ t^{\beta-1}\).

\hypertarget{c.-show-that-loglogst-beta-logalpha-beta-logt.-based-on-this-describe-a-graphical-method-for-checking-whether-or-not-the-data-is-from-a-weibull-distribution.}{%
\paragraph{\texorpdfstring{1.c. Show that
\(\log(−\log(S(t))) = \beta \log(\alpha) + \beta \log(t)\). Based on
this, describe a graphical method for checking whether or not the data
is from a Weibull
distribution.}{1.c. Show that \textbackslash{}log(−\textbackslash{}log(S(t))) = \textbackslash{}beta \textbackslash{}log(\textbackslash{}alpha) + \textbackslash{}beta \textbackslash{}log(t). Based on this, describe a graphical method for checking whether or not the data is from a Weibull distribution.}}\label{c.-show-that-loglogst-beta-logalpha-beta-logt.-based-on-this-describe-a-graphical-method-for-checking-whether-or-not-the-data-is-from-a-weibull-distribution.}}

Since \(S(t) = e^{-(\alpha t)^{\beta}}\),
\(−\log(S(t)) = (\alpha t)^{\beta}\).

Then
\(\log(−\log(S(t))) = \log((\alpha t)^{\beta}) = \beta \log(\alpha t) = \beta(\log \alpha + \log t) = \beta \log(\alpha) + \beta \log(t)\).

Based on the proved equation, we could use a log-log plot to check
whether the data is from a Weibull distribution. Check whether the data
fits a linear function \(Y = m X + b\) in the log-log plot, in which
\(Y = \log(−\log(S(t)))\), \(m = \beta\), \(X = \log t\) and
\(b = \beta \log(\alpha)\). If the data shows linearity in the log-log
plot, it is from a Weibull distribution.

\hypertarget{d.-use-the-graphical-technique-in-the-previous-question-to-check-if-a-weibull-distribution-is-appropriate-for-these-data.}{%
\paragraph{1.d. Use the graphical technique in the previous question to
check if a Weibull distribution is appropriate for these
data.}\label{d.-use-the-graphical-technique-in-the-previous-question-to-check-if-a-weibull-distribution-is-appropriate-for-these-data.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data<-}\KeywordTok{c}\NormalTok{(}\DecValTok{143}\NormalTok{, }\DecValTok{164}\NormalTok{, }\DecValTok{188}\NormalTok{, }\DecValTok{188}\NormalTok{, }\DecValTok{190}\NormalTok{, }\DecValTok{192}\NormalTok{, }\DecValTok{206}\NormalTok{, }\DecValTok{209}\NormalTok{, }\DecValTok{213}\NormalTok{, }\DecValTok{216}\NormalTok{, }\DecValTok{220}\NormalTok{, }\DecValTok{227}\NormalTok{, }\DecValTok{230}\NormalTok{, }\DecValTok{234}\NormalTok{, }\DecValTok{246}\NormalTok{, }\DecValTok{265}\NormalTok{, }\DecValTok{304}\NormalTok{)}
\NormalTok{sE<-}\KeywordTok{numeric}\NormalTok{(}\DecValTok{0}\NormalTok{)}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\KeywordTok{length}\NormalTok{(data))\{}
\NormalTok{  sE[i] =}\StringTok{ }\DecValTok{1}\OperatorTok{-}\NormalTok{(i}\FloatTok{-0.5}\NormalTok{)}\OperatorTok{/}\KeywordTok{length}\NormalTok{(data)\}}
\NormalTok{y =}\StringTok{ }\OperatorTok{-}\KeywordTok{log}\NormalTok{(sE)}
\KeywordTok{plot}\NormalTok{(data, y, }\DataTypeTok{log=}\StringTok{"xy"}\NormalTok{, }\DataTypeTok{xlab=}\StringTok{"data"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"-log(S)"}\NormalTok{)}
\NormalTok{reg=}\KeywordTok{lm}\NormalTok{(}\KeywordTok{log}\NormalTok{(y)}\OperatorTok{~}\KeywordTok{log}\NormalTok{(data))}
\KeywordTok{lines}\NormalTok{(data,}\KeywordTok{exp}\NormalTok{(}\KeywordTok{predict}\NormalTok{(reg)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW8_files/figure-latex/unnamed-chunk-1-1.pdf} From the
plot above, we could see that \(-\log(\hat{S}(t))\) and \(t\) shows
linearity in the log-log plot. As we proved in the previous question,
linearity in the log-log plot shows that these data fit a Weibull
distribution.

\hypertarget{e.-assume-that-the-weibull-distribution-is-a-good-fit-use-least-squares-approach-to-estimate-its-parameters.}{%
\paragraph{1.e. Assume that the Weibull distribution is a good fit, use
least squares approach to estimate its
parameters.}\label{e.-assume-that-the-weibull-distribution-is-a-good-fit-use-least-squares-approach-to-estimate-its-parameters.}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(reg)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = log(y) ~ log(data))
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.68997 -0.12226  0.09174  0.19153  0.30116 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -37.2330     2.1806  -17.07 3.08e-11 ***
## log(data)     6.8538     0.4073   16.83 3.80e-11 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.2871 on 15 degrees of freedom
## Multiple R-squared:  0.9497, Adjusted R-squared:  0.9463 
## F-statistic: 283.1 on 1 and 15 DF,  p-value: 3.796e-11
\end{verbatim}

As shown in the previous question, we use the least squares linear
regression in the plot to show the linearity in the log-log plot. The
estimated parameters for fitted \(Y=mX+b\) are: \(b\) = -37.233 and
\(m\) = 6.854. As we showed in 1.c, \(m = \beta\) and
\(b = \beta \log(\alpha)\). So \(\beta = m = 6.854\),
\(\alpha = e^{b/\beta} = 0.004\).

\hypertarget{a.-obtain-and-plot-the-kaplan-meier-estimates-of-s_a-and-s_b-the-corresponding-survival-functions.}{%
\paragraph{\texorpdfstring{2.a. Obtain and plot the Kaplan Meier
estimates of \(S_A\) and \(S_B\), the corresponding survival
functions.}{2.a. Obtain and plot the Kaplan Meier estimates of S\_A and S\_B, the corresponding survival functions.}}\label{a.-obtain-and-plot-the-kaplan-meier-estimates-of-s_a-and-s_b-the-corresponding-survival-functions.}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(survival)}
\NormalTok{xA<-}\KeywordTok{c}\NormalTok{(}\FloatTok{1.25}\NormalTok{, }\FloatTok{1.41}\NormalTok{, }\FloatTok{4.98}\NormalTok{, }\FloatTok{5.25}\NormalTok{, }\FloatTok{5.38}\NormalTok{, }\FloatTok{6.92}\NormalTok{, }\FloatTok{8.89}\NormalTok{, }\FloatTok{10.98}\NormalTok{, }\FloatTok{11.18}\NormalTok{, }\FloatTok{13.11}\NormalTok{, }\FloatTok{13.21}\NormalTok{, }\FloatTok{16.33}\NormalTok{, }\FloatTok{19.77}\NormalTok{, }\FloatTok{21.08}\NormalTok{, }\FloatTok{21.84}\NormalTok{, }\FloatTok{22.07}\NormalTok{, }\FloatTok{31.38}\NormalTok{, }\FloatTok{32.61}\NormalTok{, }\FloatTok{37.18}\NormalTok{, }\FloatTok{42.92}\NormalTok{)}
\NormalTok{deltaA<-}\KeywordTok{c}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{14}\NormalTok{), }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\KeywordTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{3}\NormalTok{),}\DecValTok{1}\NormalTok{)}
\NormalTok{kmA<-}\KeywordTok{survfit}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(xA,deltaA)}\OperatorTok{~}\DecValTok{1}\NormalTok{, }\DataTypeTok{type=}\StringTok{"kaplan-meier"}\NormalTok{)}
\KeywordTok{print}\NormalTok{(kmA}\OperatorTok{$}\NormalTok{surv)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 0.95 0.90 0.85 0.80 0.75 0.70 0.65 0.60 0.55 0.50 0.45 0.40 0.35 0.30
## [15] 0.30 0.24 0.24 0.24 0.24 0.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{xB<-}\KeywordTok{c}\NormalTok{(}\FloatTok{1.05}\NormalTok{, }\FloatTok{2.92}\NormalTok{, }\FloatTok{3.61}\NormalTok{, }\FloatTok{4.20}\NormalTok{, }\FloatTok{4.49}\NormalTok{, }\FloatTok{6.72}\NormalTok{, }\FloatTok{7.31}\NormalTok{, }\FloatTok{9.08}\NormalTok{, }\FloatTok{9.11}\NormalTok{, }\FloatTok{14.49}\NormalTok{, }\FloatTok{16.85}\NormalTok{, }\FloatTok{18.82}\NormalTok{, }\FloatTok{26.59}\NormalTok{, }\FloatTok{30.26}\NormalTok{, }\FloatTok{41.34}\NormalTok{)}
\NormalTok{deltaB<-}\KeywordTok{c}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{9}\NormalTok{), }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\KeywordTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{4}\NormalTok{))}
\NormalTok{kmB<-}\KeywordTok{survfit}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(xB,deltaB)}\OperatorTok{~}\DecValTok{1}\NormalTok{, }\DataTypeTok{type=}\StringTok{"kaplan-meier"}\NormalTok{)}
\KeywordTok{print}\NormalTok{(kmB}\OperatorTok{$}\NormalTok{surv)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 0.9333333 0.8666667 0.8000000 0.7333333 0.6666667 0.6000000 0.5333333
##  [8] 0.4666667 0.4000000 0.4000000 0.3200000 0.3200000 0.3200000 0.3200000
## [15] 0.3200000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(kmA}\OperatorTok{$}\NormalTok{time, kmA}\OperatorTok{$}\NormalTok{surv, }\DataTypeTok{type=}\StringTok{"s"}\NormalTok{, }\DataTypeTok{col=}\StringTok{'blue'}\NormalTok{,}\DataTypeTok{xlab=}\StringTok{"Time"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"S_A"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW8_files/figure-latex/unnamed-chunk-4-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(kmB}\OperatorTok{$}\NormalTok{time, kmB}\OperatorTok{$}\NormalTok{surv, }\DataTypeTok{type=}\StringTok{"s"}\NormalTok{, }\DataTypeTok{col=}\StringTok{'blue'}\NormalTok{,}\DataTypeTok{xlab=}\StringTok{"Time"}\NormalTok{, }\DataTypeTok{ylab=}\StringTok{"S_B"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{HW8_files/figure-latex/unnamed-chunk-5-1.pdf}

From above, we could see that Kaplan Meier estimates for \(S_A\) at
given time are: (0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55,
0.50, 0.45, 0.40, 0.35, 0.30, 0.30, 0.24, 0.24, 0.24, 0.24, 0.00).
Kaplan Meier estimates for \(S_B\) at given time are: (0.9333333,
0.8666667, 0.8, 0.7333333, 0.6666667, 0.6, 0.5333333, 0.4666667, 0.4,
0.4, 0.32, 0.32, 0.32, 0.32, 0.32).

\hypertarget{b.-estimate-s_a10-and-s_b10-using-a-95-confidence-interval.}{%
\paragraph{\texorpdfstring{2.b. Estimate \(S_A\)(10) and \(S_B\)(10)
using a 95\% confidence
interval.}{2.b. Estimate S\_A(10) and S\_B(10) using a 95\% confidence interval.}}\label{b.-estimate-s_a10-and-s_b10-using-a-95-confidence-interval.}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(kmA)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call: survfit(formula = Surv(xA, deltaA) ~ 1, type = "kaplan-meier")
## 
##   time n.risk n.event survival std.err lower 95% CI upper 95% CI
##   1.25     20       1     0.95  0.0487        0.859        1.000
##   1.41     19       1     0.90  0.0671        0.778        1.000
##   4.98     18       1     0.85  0.0798        0.707        1.000
##   5.25     17       1     0.80  0.0894        0.643        0.996
##   5.38     16       1     0.75  0.0968        0.582        0.966
##   6.92     15       1     0.70  0.1025        0.525        0.933
##   8.89     14       1     0.65  0.1067        0.471        0.897
##  10.98     13       1     0.60  0.1095        0.420        0.858
##  11.18     12       1     0.55  0.1112        0.370        0.818
##  13.11     11       1     0.50  0.1118        0.323        0.775
##  13.21     10       1     0.45  0.1112        0.277        0.731
##  16.33      9       1     0.40  0.1095        0.234        0.684
##  19.77      8       1     0.35  0.1067        0.193        0.636
##  21.08      7       1     0.30  0.1025        0.154        0.586
##  22.07      5       1     0.24  0.0980        0.108        0.534
##  42.92      1       1     0.00     NaN           NA           NA
\end{verbatim}

From the output above, we could see that the 95\% confidence interval
for \(S_A(10) = [0.471, 0.897]\).

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(kmB)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call: survfit(formula = Surv(xB, deltaB) ~ 1, type = "kaplan-meier")
## 
##   time n.risk n.event survival std.err lower 95% CI upper 95% CI
##   1.05     15       1    0.933  0.0644        0.815        1.000
##   2.92     14       1    0.867  0.0878        0.711        1.000
##   3.61     13       1    0.800  0.1033        0.621        1.000
##   4.20     12       1    0.733  0.1142        0.540        0.995
##   4.49     11       1    0.667  0.1217        0.466        0.953
##   6.72     10       1    0.600  0.1265        0.397        0.907
##   7.31      9       1    0.533  0.1288        0.332        0.856
##   9.08      8       1    0.467  0.1288        0.272        0.802
##   9.11      7       1    0.400  0.1265        0.215        0.743
##  16.85      5       1    0.320  0.1239        0.150        0.684
\end{verbatim}

From the output above, we could see that the 95\% confidence interval
for \(S_B(10) = [0.215, 0.743]\).


\end{document}
